### PR TITLE
use ansible 2.3.0.0

### PR DESCRIPTION
**Pull request by zhangjustin**
## Summary of changes

- _Make roles compatible with ansible 2.3.0.0_
- _Use jinja2 get variable value_

/fyi: _@mark-juwai , @tjoelsson_ : Please review,thanks

### CODE REVIEW

**Comment by zhangjustin** [comment]
After I create juwai-mysql pull request ,I will make a comment to tell both of you to review this issue,thanks.

**Comment by zhangjustin** [comment]
Please review ,thanks

**Review by tjoelsson — APPROVED** [review]

**Review by mark-juwai — APPROVED** [review]

**Comment by zhangjustin** [comment]
Please merge ,thanks, and I think this don't need deploy.

**Comment by tjoelsson** [comment]
Just need to confirm the new version is on galaxy

**Comment by zhangjustin** [comment]
I will confirm.

**Comment by mark-juwai** [comment]
I just did it on galaxy.

**Comment by zhangjustin** [comment]
ok

**Pull request merged**
