### PR TITLE
[EN-1416] Add RPC services to Juwai-Mysql box

### PR DESCRIPTION
**Pull request by tjoelsson**
http://jira.juwai.com/browse/EN-1416

I don't know why this was changed. Need to change it back, otherwise Python will be reinstalled every time we run this role.

@imlazyone @agirivera please review

### CODE REVIEW

**Comment by stuartwan** [comment]
Is this a bug from before? How could this work if we don't have the `python` variable before?

**Comment by tjoelsson** [comment]
It somehow works. Maybe if the variable is not defined it's just converted to a string. I'm not sure. Regardless, we should change it back.

**Comment by stuartwan** [comment]
👍

**Comment by agirivera** [comment]
:+1: Looks correct. This was from my initial confusion with ansible and should have seen it. Anyway, sorry and thanks for catching it.

**Pull request merged**
